<?php

namespace AppBundle\Repository;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends \Doctrine\ORM\EntityRepository
{

    public function searchOffer($params)
    {

        $query = $this->createQueryBuilder('o');

        if(isset($params['type'])){
            $query->andWhere('o.type = :type');
            $query->setParameter('type', $params['type']);
        }
        if(isset($params['city'])){
            $query->andWhere('o.city = :city');
            $query->setParameter('city', $params['city']);
        }
        if(isset($params['from'])){
            $query->andWhere('o.price >= :from');
            $query->setParameter('from', $params['from']);
        }

        if(isset($params['to'])){
            $query->andWhere('o.price < :to');
            $query->setParameter('to', $params['to']);
        }

        if(isset($params['transaction'])){
            $query->andWhere('o.transaction IN (:array)');
            $query->setParameter('array', $params['transaction']);
        }

        $offers = $query->getQuery()->getResult();

        return $offers;
    }

}
