root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    type: "be_simple_i18n"
    prefix:
        en: "/{_locale}/"
        fr: "/{_locale}/"
    requirements:
      _locale: fr|en
