altea_home:
    path: "/"
    defaults: { _controller: AppBundle:App:index }
about_us:
    locales:
        en: "/about-us"
        fr: "/a-propos"
    defaults: { _controller: AppBundle:App:aboutPage }
faq_page:
    path: "/faq"
    defaults: { _controller: AppBundle:App:faqPage }
privacy_page:
    locales:
        en: "/privacy"
        fr: "/vie-privee"
    defaults: { _controller: AppBundle:App:privacyPage }
legal_page:
    locales:
        en: "/legal"
        fr: "/legale"
    defaults: { _controller: AppBundle:App:legalPage }
altea_sitemap:
    path: "/sitemap.xml"
    defaults: { _controller: AppBundle:Sitemap:sitemap }
    requirements: {_format: "xml"}
send_start:
    locales:
        en: "/send-start"
        fr: "/envoyer-mail-debut"
    defaults: { _controller: AppBundle:App:sendStartMail }
search_page:
    locales:
        en: "/search"
        fr: "/chercher"
    defaults: { _controller: AppBundle:Offer:searchPage }
show_offer:
    locales:
        en: "/offer"
        fr: "/offre"
    defaults: { _controller: AppBundle:Offer:show }