altea_home:
    path: "/"
    defaults: { _controller: AppBundle:App:index }
about_us:
    locales:
        en: "/about-us"
        fr: "/a-propos"
    defaults: { _controller: AppBundle:App:aboutPage }
faq_page:
    path: "/faq"
    defaults: { _controller: AppBundle:App:faqPage }
privacy_page:
    locales:
        en: "/privacy"
        fr: "/vie-privee"
    defaults: { _controller: AppBundle:App:privacyPage }
legal_page:
    locales:
        en: "/legal"
        fr: "/legale"
    defaults: { _controller: AppBundle:App:legalPage }
media_page:
    locales:
        en: "/media"
        fr: "/medias"
    defaults: { _controller: AppBundle:App:mediaPage }
altea_sitemap:
    path: "/sitemap.xml"
    defaults: { _controller: AppBundle:Sitemap:sitemap }
    requirements: {_format: "xml"}
send_start:
    locales:
        en: "/send-start"
        fr: "/envoyer-mail-debut"
    defaults: { _controller: AppBundle:App:sendStartMail }
search_page:
    locales:
        en: "/search"
        fr: "/chercher"
    defaults: { _controller: AppBundle:Offer:searchPage }
show_offer:
    locales:
        en: "/offer/{url}/{id}"
        fr: "/offre/{url}/{id}"
    defaults: { _controller: AppBundle:Offer:show }
    requirements:
        url:    .*
delete_all:
    locales:
        en: "/delete-all"
        fr: "/effacer-tout"
    defaults: { _controller: AppBundle:Offer:deleteAll }
process_offer:
    locales:
        en: "/process-offer"
        fr: "/traiter-offre"
    defaults: { _controller: AppBundle:Offer:processOffers }
contact_us:
    locales:
        en: "/contact-us"
        fr: "/contacter-nous"
    defaults: { _controller: AppBundle:Contact:contactUsPage }
altea_contact:
    locales:
        en: "/contact"
        fr: "/contacter"
    defaults: { _controller: AppBundle:Contact:contact }
offer_contact:
    locales:
        en: "/offer-contact"
        fr: "/offre-contacter"
    defaults: { _controller: AppBundle:Contact:contactOffer }
altea_sitemap:
    path: "/sitemap.xml"
    defaults: { _controller: AppBundle:Sitemap:sitemap }
    requirements: {_format: "xml"}