#    ai_altea.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
services:
  app.offer_generate_url:
        class: AppBundle\Service\GenerateUrl
        arguments: ['@translator']
  app.find_latlong:
      class: AppBundle\Service\FindLatLong
  app.offer_image:
        class: AppBundle\Service\Namer
        tags:
          - { name: namer }





